packages:
  - .
  - ./website

catalog:
  '@actions/core': ^3.0.0
  '@actions/github': ^9.0.0
  '@github/copilot-sdk': ^0.1.25
  '@octokit/webhooks': ^14.2.0
  '@schplitt/eslint-config': ^1.3.0
  '@tmcp/adapter-valibot': ^0.1.5
  '@tmcp/transport-http': ^0.8.4
  '@toon-format/toon': ^2.1.0
  bumpp: ^10.4.1
  changelogithub: ^14.0.0
  consola: ^3.4.2
  defu: ^6.1.4
  eslint: ^9.39.2
  h3: ^1.15.4
  nitropack: ^2.13.1
  octokit: ^5.0.5
  srvx: ^0.11.7
  tinyexec: ^1.0.2
  tmcp: ^1.19.2
  tsdown: ^0.20.3
  typescript: ^5.9.3
  valibot: ^1.2.0
  vitest: ^4.0.18

catalogMode: prefer

onlyBuiltDependencies:
  - esbuild

shellEmulator: true

trustPolicy: no-downgrade

trustPolicyExclude:
  - cached-factory@0.1.0
  - ts-api-utils@2.2.0
  - undici-types@6.21.0
